name: CI

on:
  push:
    branches: [master]

permissions:
  contents: write

jobs:
  node-js:
    name: Node.js
    runs-on: ubuntu-latest
    concurrency: ci-${{ github.ref }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: 'true'
      
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'pnpm'
          cache-dependency-path: '**/pnpm-lock.yaml'

      - name: Install Packages
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm run build
