name: Node.js CI

on:
  push:
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Packages
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install

      - name: Lint
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: dev:lint
